theme: jekyll-theme-cayman
title: README.md boilerplate
show_downloads: true
description: Template to write beautiful readme files faster
plugins:
  - jemoji
  - jekyll-relative-links
relative_links:
  enabled: true
include:
  - README.md
